# Generated by Django 5.2.6 on 2025-09-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0005_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='flux.ticket'),
            preserve_default=False,
        ),
    ]
